# Generated by Django 4.2.7 on 2023-11-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_code', models.AutoField(primary_key=True, serialize=False)),
                ('client_type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff_code', models.AutoField(primary_key=True, serialize=False)),
                ('call_type', models.CharField(max_length=50)),
                ('cost_per_minute', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('client_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_system.client')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_code', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('conversation_minutes', models.IntegerField()),
                ('tariff_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_system.tariff')),
            ],
        ),
    ]
